name: Manki Test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: Generate Anki Questions of "Manki"-Project
        id: manki
        uses: raverank/manki@gh-action
        with:
          project-root: './plain'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Generate Anki Questions Package
          branch: question-generator/patch
          branch-suffix: timestamp
          delete-branch: true
