name: Manki Markdown To Anki Conversion

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: Generate Anki Questions of manki-project
        id: manki
        uses: raverank/manki@v1.0.0
        with:
          project-root: './plain'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Generate Anki Questions Package
          branch: question-generator/patch
          title: Add generated manki Anki-Package
          body: "Result of the conversion:\n ${{ steps.manki.outputs.conversion-log }}"
